"use strict";Object.defineProperties(exports,{__esModule:{value:!0},[Symbol.toStringTag]:{value:"Module"}});const t=require("lit/decorators.js"),u=require("lit"),y=require("lit/directives/class-map.js"),b=require("lit/directives/style-map.js");require("../../utils/pictograms.cjs");const a=require("../../utils/color.cjs"),d=require("./zwc-button_styles.cjs"),p=require("lit/static-html.js");var h=Object.defineProperty,w=Object.getOwnPropertyDescriptor,e=(i,o,r,l)=>{for(var s=l>1?void 0:l?w(o,r):o,n=i.length-1,c;n>=0;n--)(c=i[n])&&(s=(l?c(o,r,s):c(s))||s);return l&&s&&h(o,r,s),s};exports.ZwcButton=class extends u.LitElement{constructor(){super(...arguments),this.type="button",this.size="lg",this.status="primary",this.text="",this.isInverted=!1,this.isDisabled=!1,this.isIconAlt=!1,this.color=void 0,this.backgroundColor=void 0}render(){const i={btn:!0,[`btn--${this.status}`]:this.status,[`btn--${this.size}`]:this.size,inverted:this.isInverted,disabled:this.isDisabled,alt:this.isIconAlt},o={color:this.color?a.getColorVar(this.color):null,backgroundColor:this.backgroundColor?a.getColorVar(this.backgroundColor):null},r=this.type==="button"?p.literal`button`:p.literal`a`;return p.html`
        <${r} class="${y.classMap(i)}" style="${b.styleMap(o)}">
            ${this.text}
            <slot name="icon"></slot>
            <slot name="badge"></slot>
            <slot></slot>
        </${r}>
    `}};exports.ZwcButton.styles=u.unsafeCSS(d);e([t.property()],exports.ZwcButton.prototype,"type",2);e([t.property()],exports.ZwcButton.prototype,"size",2);e([t.property()],exports.ZwcButton.prototype,"status",2);e([t.property({type:String,attribute:"text"})],exports.ZwcButton.prototype,"text",2);e([t.property({type:Boolean,attribute:"inverted"})],exports.ZwcButton.prototype,"isInverted",2);e([t.property({type:Boolean,attribute:"disabled"})],exports.ZwcButton.prototype,"isDisabled",2);e([t.property({type:Boolean,attribute:"alt"})],exports.ZwcButton.prototype,"isIconAlt",2);e([t.property({type:String})],exports.ZwcButton.prototype,"color",2);e([t.property({type:String})],exports.ZwcButton.prototype,"backgroundColor",2);exports.ZwcButton=e([t.customElement("zwc-button")],exports.ZwcButton);
//# sourceMappingURL=zwc-button.cjs.map
